# Generated by Django 4.0.4 on 2022-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_info_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_before',
            field=models.FloatField(null=True),
        ),
    ]
