# Generated by Django 4.0.4 on 2022-07-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_price_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_before',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
